version: "3.9"
services:
  mercure:
    container_name: mercure_container
    image: dunglas/mercure
    restart: unless-stopped
    environment:
      SERVER_NAME: ':80'
      MERCURE_PUBLISHER_JWT_KEY: '!ChangeMe!'
      MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeMe!'
    ports:
      - "80:80"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
  database:
    container_name: mysql_container
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - mysql
    restart: unless-stopped
networks:
  mysql:
    driver: bridge

volumes:
  mysql:
  caddy_data:
  caddy_config:
